[package]
name = "equart"
version = "0.2.0"
authors = ["George Shuklin <george.shuklin@gmail.com>"]
edition = "2018"

[dependencies]
piston = "*"
piston_window = "*"
image = "*"
vecmath = "*"
rand = "*"
num_cpus = "*"
gfx_device_gl = "*"
array2d = "*"
