[package]
name = "druw"
version = "0.1.0"
authors = ["George Shuklin <george.shuklin@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.11.2"
itertools = "0.8.0"
clipboard = "0.5.0"
lodepng = "2.4.2"
