[package]
name = "equart"
version = "0.1.0"
authors = ["George Shuklin <george.shuklin@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
# clipboard = "0.5.0"
# lodepng = "2.4.2"
piston = "0.49.0"
piston_window = "0.107.0"
image = "0.23.0"
